networks:
  default:
    external:
      name: roboshop
services:
  mongodb:
    image: mongodb:1
    networks:
    - reboshop 

  catalogue:
    image: catalogue:1
    networks:
    - roboshop
    depends_on: 
    - mongodb
  
  web:
    image: web:1
    ports: 
    - "80:80"
    networks:
    - roboshop
    depends_on:
    - catalogue